// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsworkmail
{
    [AwsworkmailResourceType("awsworkmail:index:CognitoEmailSender")]
    public partial class CognitoEmailSender : global::Pulumi.CustomResource
    {
        [Output("kmsKeyArn")]
        public Output<string> KmsKeyArn { get; private set; } = null!;

        [Output("lambdaArn")]
        public Output<string> LambdaArn { get; private set; } = null!;

        [Output("userPoolId")]
        public Output<string> UserPoolId { get; private set; } = null!;


        /// <summary>
        /// Create a CognitoEmailSender resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CognitoEmailSender(string name, CognitoEmailSenderArgs args, CustomResourceOptions? options = null)
            : base("awsworkmail:index:CognitoEmailSender", name, args ?? new CognitoEmailSenderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CognitoEmailSender(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("awsworkmail:index:CognitoEmailSender", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/gothub-team",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CognitoEmailSender resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CognitoEmailSender Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new CognitoEmailSender(name, id, options);
        }
    }

    public sealed class CognitoEmailSenderArgs : global::Pulumi.ResourceArgs
    {
        [Input("kmsKeyArn", required: true)]
        public Input<string> KmsKeyArn { get; set; } = null!;

        [Input("lambdaArn", required: true)]
        public Input<string> LambdaArn { get; set; } = null!;

        [Input("userPoolId", required: true)]
        public Input<string> UserPoolId { get; set; } = null!;

        public CognitoEmailSenderArgs()
        {
        }
        public static new CognitoEmailSenderArgs Empty => new CognitoEmailSenderArgs();
    }
}
