// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsworkmail
{
    [AwsworkmailResourceType("awsworkmail:index:DefaultDomain")]
    public partial class DefaultDomain : global::Pulumi.CustomResource
    {
        [Output("clientToken")]
        public Output<string?> ClientToken { get; private set; } = null!;

        [Output("domainName")]
        public Output<string> DomainName { get; private set; } = null!;

        [Output("organizationId")]
        public Output<string> OrganizationId { get; private set; } = null!;

        [Output("records")]
        public Output<ImmutableArray<Outputs.DnsRecord>> Records { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a DefaultDomain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DefaultDomain(string name, DefaultDomainArgs args, CustomResourceOptions? options = null)
            : base("awsworkmail:index:DefaultDomain", name, args ?? new DefaultDomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DefaultDomain(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("awsworkmail:index:DefaultDomain", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/gothub-team",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DefaultDomain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DefaultDomain Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DefaultDomain(name, id, options);
        }
    }

    public sealed class DefaultDomainArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientToken")]
        public Input<string>? ClientToken { get; set; }

        [Input("domainName", required: true)]
        public Input<string> DomainName { get; set; } = null!;

        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public DefaultDomainArgs()
        {
        }
        public static new DefaultDomainArgs Empty => new DefaultDomainArgs();
    }
}
