// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsworkmail
{
    [AwsworkmailResourceType("awsworkmail:index:WorkmailRegistration")]
    public partial class WorkmailRegistration : global::Pulumi.CustomResource
    {
        [Output("emailPrefix")]
        public Output<string> EmailPrefix { get; private set; } = null!;

        [Output("entityId")]
        public Output<string> EntityId { get; private set; } = null!;

        [Output("organizationId")]
        public Output<string> OrganizationId { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a WorkmailRegistration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public WorkmailRegistration(string name, WorkmailRegistrationArgs args, CustomResourceOptions? options = null)
            : base("awsworkmail:index:WorkmailRegistration", name, args ?? new WorkmailRegistrationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private WorkmailRegistration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("awsworkmail:index:WorkmailRegistration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/gothub-team",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing WorkmailRegistration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static WorkmailRegistration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new WorkmailRegistration(name, id, options);
        }
    }

    public sealed class WorkmailRegistrationArgs : global::Pulumi.ResourceArgs
    {
        [Input("emailPrefix", required: true)]
        public Input<string> EmailPrefix { get; set; } = null!;

        [Input("entityId", required: true)]
        public Input<string> EntityId { get; set; } = null!;

        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public WorkmailRegistrationArgs()
        {
        }
        public static new WorkmailRegistrationArgs Empty => new WorkmailRegistrationArgs();
    }
}
