# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .organization import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_awsworkmail.types as __types
    types = __types
else:
    types = _utilities.lazy_import('pulumi_awsworkmail.types')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "awsworkmail",
  "mod": "index",
  "fqn": "pulumi_awsworkmail",
  "classes": {
   "awsworkmail:index:Organization": "Organization"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "awsworkmail",
  "token": "pulumi:providers:awsworkmail",
  "fqn": "pulumi_awsworkmail",
  "class": "Provider"
 }
]
"""
)
