// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsworkmail.Types.Inputs
{

    public sealed class DomainArgs : global::Pulumi.ResourceArgs
    {
        public DomainArgs()
        {
        }
        public static new DomainArgs Empty => new DomainArgs();
    }
}
