// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsworkmail.Outputs
{

    [OutputType]
    public sealed class DnsRecord
    {
        public readonly string Hostname;
        public readonly string Type;
        public readonly string Value;

        [OutputConstructor]
        private DnsRecord(
            string hostname,

            string type,

            string value)
        {
            Hostname = hostname;
            Type = type;
            Value = value;
        }
    }
}
