// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsworkmail.Outputs
{

    [OutputType]
    public sealed class Domain
    {
        public readonly string DomainName;
        public readonly string HostedZoneId;

        [OutputConstructor]
        private Domain(
            string domainName,

            string hostedZoneId)
        {
            DomainName = domainName;
            HostedZoneId = hostedZoneId;
        }
    }
}
