// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CognitoEmailSender extends pulumi.CustomResource {
    /**
     * Get an existing CognitoEmailSender resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CognitoEmailSender {
        return new CognitoEmailSender(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'awsworkmail:index:CognitoEmailSender';

    /**
     * Returns true if the given object is an instance of CognitoEmailSender.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CognitoEmailSender {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CognitoEmailSender.__pulumiType;
    }

    public readonly kmsKeyArn!: pulumi.Output<string>;
    public readonly lambdaArn!: pulumi.Output<string>;
    public readonly userPoolId!: pulumi.Output<string>;

    /**
     * Create a CognitoEmailSender resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CognitoEmailSenderArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.kmsKeyArn === undefined) && !opts.urn) {
                throw new Error("Missing required property 'kmsKeyArn'");
            }
            if ((!args || args.lambdaArn === undefined) && !opts.urn) {
                throw new Error("Missing required property 'lambdaArn'");
            }
            if ((!args || args.userPoolId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userPoolId'");
            }
            resourceInputs["kmsKeyArn"] = args ? args.kmsKeyArn : undefined;
            resourceInputs["lambdaArn"] = args ? args.lambdaArn : undefined;
            resourceInputs["userPoolId"] = args ? args.userPoolId : undefined;
        } else {
            resourceInputs["kmsKeyArn"] = undefined /*out*/;
            resourceInputs["lambdaArn"] = undefined /*out*/;
            resourceInputs["userPoolId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CognitoEmailSender.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CognitoEmailSender resource.
 */
export interface CognitoEmailSenderArgs {
    kmsKeyArn: pulumi.Input<string>;
    lambdaArn: pulumi.Input<string>;
    userPoolId: pulumi.Input<string>;
}
