// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class WorkmailRegistration extends pulumi.CustomResource {
    /**
     * Get an existing WorkmailRegistration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): WorkmailRegistration {
        return new WorkmailRegistration(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'awsworkmail:index:WorkmailRegistration';

    /**
     * Returns true if the given object is an instance of WorkmailRegistration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkmailRegistration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkmailRegistration.__pulumiType;
    }

    public readonly emailPrefix!: pulumi.Output<string>;
    public readonly entityId!: pulumi.Output<string>;
    public readonly organizationId!: pulumi.Output<string>;
    public readonly region!: pulumi.Output<string>;

    /**
     * Create a WorkmailRegistration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkmailRegistrationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.emailPrefix === undefined) && !opts.urn) {
                throw new Error("Missing required property 'emailPrefix'");
            }
            if ((!args || args.entityId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'entityId'");
            }
            if ((!args || args.organizationId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["emailPrefix"] = args ? args.emailPrefix : undefined;
            resourceInputs["entityId"] = args ? args.entityId : undefined;
            resourceInputs["organizationId"] = args ? args.organizationId : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
        } else {
            resourceInputs["emailPrefix"] = undefined /*out*/;
            resourceInputs["entityId"] = undefined /*out*/;
            resourceInputs["organizationId"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkmailRegistration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a WorkmailRegistration resource.
 */
export interface WorkmailRegistrationArgs {
    emailPrefix: pulumi.Input<string>;
    entityId: pulumi.Input<string>;
    organizationId: pulumi.Input<string>;
    region: pulumi.Input<string>;
}
